image: python:3.9

variables:
  POETRY_HOME: "$CI_PROJECT_DIR/.poetry"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pypoetry"

cache:
  paths:
    - .poetry
    - .cache/pypoetry

test:compass-modules:
  script:
    - module load pleque/master
    - pytest tests/test_cdb.py
    - module purge
    - module load pleque/develop
    - pytest tests/test_cdb.py
    - module purge
    - module load pleque/unstable
    - pytest tests/test_cdb.py
    - module purge
    - module load pleque/sumtraic2023
    - module purge
  tags:
    - soroban-node-01

test:pytest:
  script:
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="$POETRY_HOME/bin:$PATH"
    - poetry config virtualenvs.create false
    - poetry install --without compass --with omas
    - pytest
