image: continuumio/miniconda3

before_script:
  - conda env create -f environment.yml
  - source activate pleque

test:pylint:
  script:
    - pylint pleque

test:flake8:
  script:
  - flake8 -max-line-length 121 pleque

# TODO add pytest
